name: GFPS
main: org.mgenterprises.java.bukkit.gfps.GFPS
version: 0.1
commands:
  join:
    description: Join a game
    usage: /join [Game Name]
  leave:
    description: Leave the game
    usage: /leave
  game:
    description: Command for modifing command
    usage: /game 
  top:
    description: See scores
    usage: /top
  score:
    description: See your score
    usage: /score
  weapons:
    description: List guns enabled in game
    usage: /weapons